---
#
# ansible-playbook -i env/inventory bolt-aws-cloudfront-s3.yml -l shared

- name: 'Bolt AWS CloudFront S3'
  gather_facts: false
  hosts: 'aws_all'
  connection: 'local'

  tasks:
    - name: 'Provision a AWS S3 bucket (+ expose it via a CloudFront distribution) to store and accessfiles'
      cloudformation:
        stack_name: '{{ app_name }}-stack'
        state: '{{ app_state }}'
        region: '{{ aws_region }}'
        profile: '{{ aws_profile }}'
        template_body: "{{lookup('template', 'templates/aws_bolt_cloudfront_s3.yml.j2')}}"
        template_parameters: '{{ cf_tpl_paramters }}'
        termination_protection: true
